<?php return array (
  'email_type' => '1',
  'email_safe' => 'ssl',
  'mail_address' => '468650996@qq.com',
  'smtp' => 'smtp.qq.com',
  'smtp_user' => '468650996',
  'smtp_pwd' => 'pltqbqgcufbebicc',
  'smtp_port' => '465',
  'order_by' => 'new',
  'name' => '云耕耘',
  'url' => 'http://www.yungengyun.com',
  'master' => '',
  'qq' => '',
  'email' => '',
  'mobile' => '15838281830',
  'phone' => '',
  'address' => '',
  'site_footer_code' => '<div class=\\"footer\\" style=\\"text-align:center;\\">	<p class=\\"links\\">		<a href=\\"\\">关于我们</a>|<a href=\\"\\">常见问题</a>|<a href=\\"\\">安全交易</a>|<a href=\\"\\">购买流程</a>|<a href=\\"\\">如何付款</a>|<a href=\\"\\">联系我们</a>|<a href=\\"\\">合作提案</a>	</p>	<p class=\\"copyright\\">		Powered by <a href=\\"http://www.yungengyun.com\\">iWebShop</a>	</p>Copyright © 2005-2014 <a class=\\"copyys\\" target=\\"_blank\\" href=\\"http://www.miibeian.gov.cn/\\">X</a>XXXXX备XXXXXXX号</div>',
  'tax' => '10',
  'stockup_time' => '0',
  'index_seo_title' => '源码分享,视频分享,书籍分享,资料分享,软件分享',
  'index_seo_keywords' => '源码分享,视频分享,书籍分享,资料分享,软件分享,个人入驻,商家入驻,免费分享',
  'index_seo_description' => '一分耕耘,一份收获。云耕耘平台为用户提供免费的源码、视频、书籍、资料、软件等资源。',
  'goods_no_pre' => 'ygy',
  'commission' => '5',
  'store_num_warning' => '1',
  'reg_option' => '1',
  'sms_platform' => 'zhutong',
  'sms_userid' => '',
  'sms_username' => '',
  'sms_pwd' => '',
  'test_address' => '1608626550@qq.com',
  'logo' => 'upload/2018/11/05/20181105100311320.png',
)?>