<?php return array (
  'email_type' => '1',
  'email_safe' => '',
  'mail_address' => '',
  'smtp' => '',
  'smtp_user' => '',
  'smtp_pwd' => '',
  'smtp_port' => '',
  'order_by' => 'new',
  'name' => '211gou电子商务平台',
  'url' => 'http://www.211gou.com',
  'master' => '',
  'qq' => '',
  'email' => '',
  'mobile' => '15838281830',
  'phone' => '',
  'address' => '',
  'site_footer_code' => '<div class=\\"footer\\" style=\\"text-align:center;\\">	<p class=\\"links\\">		<a href=\\"\\">关于我们</a>|<a href=\\"\\">常见问题</a>|<a href=\\"\\">安全交易</a>|<a href=\\"\\">购买流程</a>|<a href=\\"\\">如何付款</a>|<a href=\\"\\">联系我们</a>|<a href=\\"\\">合作提案</a>	</p>	<p class=\\"copyright\\">		Powered by <a href=\\"http://www.aircheng.com\\">iWebShop</a>	</p>Copyright © 2005-2014 <a class=\\"copyys\\" target=\\"_blank\\" href=\\"http://www.miibeian.gov.cn/\\">X</a>XXXXX备XXXXXXX号</div>',
  'tax' => '10',
  'stockup_time' => '1',
  'index_seo_title' => '211gou商城系统',
  'index_seo_keywords' => '大学生购物平台，大学生商城',
  'index_seo_description' => '211gou是基于php开发b2c2c开源多用户商城系统,支持商家入驻,支持微商城,手机移动商城,APP商城多为一体的电子商务系统',
  'goods_no_pre' => 'GOU',
  'commission' => '',
  'store_num_warning' => '1',
  'reg_option' => '0',
  'sms_platform' => 'zhutong',
  'sms_userid' => '',
  'sms_username' => '',
  'sms_pwd' => '',
)?>